import { Product, Review } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'bed',
    nameBn: 'চিটাগাং সেগুন কাঠের খোদাই রাজকীয় খাট',
    nameEn: 'Chittagong Teak Royal Bed',
    category: 'furniture',
    imgUrl: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&w=800&q=80',
    priceRangeBn: '৩৫,০০০ - ১,৫০,০০০ ৳',
    priceRangeEn: '35,000 - 150,000 BDT',
    minPrice: 35000,
    descriptionBn: '১০০% খাঁটি চিটাগাং সেগুন কাঠ দিয়ে তৈরি অত্যন্ত আকর্ষনীয় ও টেকসই রাজকীয় ডাবল খাট। দক্ষ কারিগর দ্বারা সম্পূর্ণ হাতে খোদাই করা অনন্য ফুলের কারুকাজ ও মসৃণ ডলফিন গ্লসি ল্যাকার ফিনিশ যা আপনার বেডরুমের সৌন্দর্য দ্বিগুণ বাড়িয়ে দেবে।',
    descriptionEn: 'Premium luxury double bed carved by skilled artisans using 100% pure seasoned Chittagong Teak wood, showcasing gorgeous hand carvings and a durable gloss lacquer finish.',
    specsBn: ['খাঁটি চিটাগাং সেগুন কাঠ', 'সম্পূর্ণ মেজারমেন্ট কাস্টমাইজড', 'উচ্চমানের ডলফিন গ্লসি বার্নিশ', 'আজীবন ঘুনে না ধরার গ্যারান্টি', 'সাইজঃ ৬ ফুট x ৭ ফুট (কিং সাইজ)'],
    specsEn: ['Pure Chittagong Teak Wood', 'Fully Customizable Specifications', 'Premium Dolphin Gloss Varnish', 'Lifetime Anti-borer Guard', 'Standard King Size: 6ft x 7ft'],
    isTrending: true
  },
  {
    id: 'sofa',
    nameBn: 'সেগুন কাঠের রাজকীয় কুশন সোফা সেট',
    nameEn: 'Traditional Royal Sofa Set',
    category: 'furniture',
    imgUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80',
    priceRangeBn: '৪৫,০০০ - ১,২০,০০০ ৳',
    priceRangeEn: '45,000 - 120,000 BDT',
    minPrice: 45000,
    descriptionBn: 'আপনার ড্রয়িং রুমের রাজকীয় অলঙ্করণের জন্য সেরা পছন্দ এই আকর্ষক সেগুন কাঠের সোফা সেট। আরামদায়ক হাই-ডেনসিটি ফোম ড্রনিল কুশন এবং নজরকাড়া দেশীয় ঐতিহ্যবাহী খোদাই কাজ ও আকর্ষণীয় উড মোটিফ একে করেছে অত্যন্ত দৃষ্টিনন্দন।',
    descriptionEn: 'Elegant sovereign living room sofa set styled with traditional hand engravings, seasoned teak framework, and premium high-density foam cushions.',
    specsBn: ['জেনারেল সেগুন কাঠ বডি', '৩+২+১ ক্লাসিক সিটার ডেকোরেশন', 'পরিবর্তনযোগ্য মখমল রাজকীয় কাপড়', 'হাই-ডেনসিটি আরামদায়ক ফোম', '১০ বছরের ওয়ারেন্টি'],
    specsEn: ['Seasoned Teak Wood Base', '3+2+1 Traditional Seater Unit', 'Changeable Tufted Royal Fabric', 'Export Quality Orthopaedic Foam', '10-Year Form Warranty'],
    isTrending: true
  },
  {
    id: 'dining',
    nameBn: 'পারফেক্ট সেগুন কাঠের রাজকীয় ডাইনিং টেবিল',
    nameEn: 'Teak Luxury Dining Set',
    category: 'furniture',
    imgUrl: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=800&q=80',
    priceRangeBn: '২৫,০০০ - ৮০,০০০ ৳',
    priceRangeEn: '25,000 - 80,000 BDT',
    minPrice: 25000,
    descriptionBn: 'পরিবারের খাবার টেবিলের আড্ডায় আভিজাত্য আনতে আমাদের এই খাটি সেগুন কাঠের মজবুত ৬-চেয়ার ডাইনিং টেবিল সেট। ১০মিমি হেভি টেম্পারড গ্লাস টপ এবং আকর্ষণীয় খোদাই করা চেয়ারের চমৎকার ডিজাইন ঘরকে দেবে সম্পূর্ণ ঐতিহ্যবাহী লুক।',
    descriptionEn: 'Bring traditional Bangladeshi visual legacy to your family dining space with this solid teak wood dining set, carrying 6 high-backed cushion chairs.',
    specsBn: ['১টি প্রিমিয়াম টেবিল ও ৬টি খোদাই চেয়ার', '১০মিমি টেম্পারড গ্লাস টপ সাপোর্ট', 'বিশেষ ওয়াটার-রেজিস্ট্যান্ট কোটিং', 'মিহি হ্যান্ড কার্ভ ডিজাইন', '৫০ বছরেরও বেশি স্থায়িত্ব'],
    specsEn: ['1 Premium Table & 6 Carved Chairs', '10mm Toughened Glass Top Included', 'Scratch & Heat Resistant Varnish', 'Meticulous Finger Joint Assembly', 'Over 50 Years Estimated Lifespan']
  },
  {
    id: 'almirah',
    nameBn: '৪-পাল্লা বার্মিজ সেগুন কাঠের আলমারি',
    nameEn: 'Wooden Carved Wardrobe',
    category: 'furniture',
    imgUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=800&q=80',
    priceRangeBn: '৩০,০০০ - ৯০,০০০ ৳',
    priceRangeEn: '30,000 - 90,000 BDT',
    minPrice: 30000,
    descriptionBn: 'বার্মিজ সেগুন কাঠের নকশাকৃত অত্যন্ত মজবুত ও সুরক্ষিত ৪-পাল্লার আলমারি। এর ভেতরে রয়েছে একাধিক শেলফ, হ্যাঙ্গার স্পেস এবং সম্পূর্ণ সেফটি লক সিকিউরিটি ভল্ট যা আপনার কাপড় ও মূল্যবান সামগ্রী সুরক্ষিত রাখবে।',
    descriptionEn: 'Spacious highly fortified 4-door wardrobe assembled from hand-seasoned Burmese Teak. Fitted with dynamic hanging racks and a secure steel safety vault.',
    specsBn: ['খাঁটি বার্মিজ সেগুন প্লেট', 'ডিজিটাল হেভি মেটাল লক', '৪টি প্রশস্ত দরজার ক্যাবিনেট', 'পানি প্রতিরোধের ল্যাকার পলিশ', '১০০% ঘুণপ্রতিরোধক'],
    specsEn: ['Authentic Burmese Teak Planks', 'Heavy Metal Multi-lock Hardware', '4 Extra Wide Hinged Doors', 'Waterproof Sheen Lacquer Polish', '100% Termite Repellent Shell']
  },
  {
    id: 'dressing-table',
    nameBn: 'সেগুন কাঠের ভ্যানিটি ড্রেসিং টেবিল',
    nameEn: 'Teak Carved Dressing Table',
    category: 'furniture',
    imgUrl: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=800&q=80',
    priceRangeBn: '১৮,০০০ - ৬০,০০০ ৳',
    priceRangeEn: '18,000 - 60,000 BDT',
    minPrice: 18000,
    descriptionBn: 'আপনার বেডরুমের আভিজাত্য বাড়াতে তৈরি করা আকর্ষণীয় ৪-ড্রয়ার বিশিষ্ট স্টোরেজ ড্রেসিং টেবিল। এতে রয়েছে দৃষ্টিনন্দন ডিজাইনের আয়না এবং প্রসাধন সামগ্রী সুন্দরভাবে গুছিয়ে রাখতে একাধিক ছোট ও বড় ড্রয়ার ক্যাবিনেট।',
    descriptionEn: 'Bespoke hand-carved solid teak vanity dressing console unit. Ideal for organizing makeup kits and bedroom accessories in traditional style.',
    specsBn: ['৪টি ডিপ স্লাইডিং ম্যাজিক ড্রয়ার', 'উচ্চমানের মজবুত বেলজিয়াম গ্লাস', 'সাইলেন্ট স্মুথ চ্যানেল ড্রয়ার', 'ডলফিন চকচকে কাঠের ফিনিশ', 'মেজারমেন্ট কাস্টমাইজেশনের সুবিধা'],
    specsEn: ['4 Deep-sliding Premium Drawers', 'Imported High-Clarity Glass', 'Smooth Ball-bearing Slide Tracks', 'High-gloss Walnut Suede Finish', 'Bespoke Custom Designing']
  },
  {
    id: 'rocker-chair',
    nameBn: 'সেগুন কাঠের আরামদায়ক রকিং ইজি চেয়ার',
    nameEn: 'Classic Wooden Rocking Chair',
    category: 'furniture',
    imgUrl: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?auto=format&fit=crop&w=800&q=80',
    priceRangeBn: '৬,০০০ - ২৫,০০০ ৳',
    priceRangeEn: '6,000 - 25,000 BDT',
    minPrice: 6000,
    descriptionBn: 'ঘরের বারান্দায় অলস বিকেলের চা উপভোগ ও অবসাদ কাটাতে এই রকিং চেয়ারটি অতুলনীয়। বার্মিজ সেগুন কাঠের সুক্ষ্ম খোদাই করা হাতল এবং পিঠের চমৎকার অর্গোনমিক ডবল কুশন বা পিঠের সাপোর্ট যা অবসাদ দূর করতে অসম্ভব আরামদায়ক।',
    descriptionEn: 'Experience pure relaxation on the balcony or reading nook with this traditional rocking easy chair crafted in premium teak wood with ergonomic curved support.',
    specsBn: ['পারফেক্ট মসৃণ রকিং ব্যালেন্স', 'অর্গোনমিক ব্যাকরেস্ট সাপোর্ট', 'চিটাগাং সেগুন কাঠের ফ্রেম', '১০০% ড্রাই ও সিজনড কাঠ', '৫ বছরের মেকিং ওয়ারেন্টি'],
    specsEn: ['Flawless Rocking Equilibrium', 'Spinal Alignment Slat Back', 'Solid Teak Hardwood frame', '100% Seasoned and Dried Timber', '5-Year structural warranty']
  },
  {
    id: 'showcase',
    nameBn: 'সেগুন কাঠের রাজকীয় ডাইনিং প্রদর্শন শোকেস',
    nameEn: 'Regal Wooden Display Showcase',
    category: 'furniture',
    imgUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    priceRangeBn: '২০,০০০ - ৭০,০০০ ৳',
    priceRangeEn: '20,000 - 70,000 BDT',
    minPrice: 20000,
    descriptionBn: 'ডাইনিং বা ড্রয়িং রুমের সৌন্দর্য বৃদ্ধির জন্য সেরা আসবাব কাঁচ সংলগ্ন শোকেস। মূল্যবান মেডেল, ক্রেস্ট বা শখের কাঁচের তৈজসপত্র সাজিয়ে রাখার জন্য ৩-স্তর বিশিষ্ট মজবুত কাঁচের তাক ও নিচের পার্টের বড় স্টোরেজ বক্স রাজকীয় মুকুট নকশা সহ।',
    descriptionEn: 'A magnificent wooden display cabinet to showcase your finest ceramic cutlery and awards under secure ambient layouts.',
    specsBn: ['৩-স্তর বিশিষ্ট টেম্পারড গ্লাস', 'খোদাইকৃত ট্রেডিশনাল রাজকীয় মুকুট', 'লোকাল সেগুন কাঠ পলিশিং ফিনিশ', 'ব্রাস বোল্ট ও মেটাল নবস', 'নিচে লক সহ চমৎকার ড্রয়ার'],
    specsEn: ['3-tier Heavy-duty Glass Shelving', 'Classical Crown Hand Carving', 'Local Premium Teak Polish Matte', 'Vintage Brass Handles & Latches', 'Spacious Base Cabinets with Lock']
  },
  {
    id: 'study-table',
    nameBn: 'মেহগনি কাঠের রাজকীয় রিডিং টেবিল ও চেয়ার',
    nameEn: 'Royal Wooden Writing Desk',
    category: 'furniture',
    imgUrl: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=800&q=80',
    priceRangeBn: '১২,০০০ - ৪০,০০০ ৳',
    priceRangeEn: '12,000 - 40,000 BDT',
    minPrice: 12000,
    descriptionBn: 'যশোরের প্রিমিয়াম মেহগনি কাঠ দ্বারা নির্মিত টেকসই এবং দীর্ঘস্থায়ী স্টাডি টেবিল-চেয়ার সেট। বই রাখার জন্য আলাদা ডবল র্যাক এবং ড্রয়ারসহ আপনার পড়াশোনা ও অফিশিয়াল সব কাজের জন্য উপযুক্ত ও আড়ম্বরপূর্ণ কাজ।',
    descriptionEn: 'Robust and highly polished Jessore Mahogany timber study writing unit paired with an ergonomic design comfort wooden chair.',
    specsBn: ['১০০% যশোর মেহগনি কাঠ', 'অন্তর্নির্মিত বই রাখার ডবল র্যাক', 'কীবোর্ড স্লাইড ও ড্রয়ার লক সমৃদ্ধ', 'মসৃণ মেলামাইন অ্যান্টি-স্ক্র্যাচ টপ', '৩ বছরের সম্পূর্ণ গ্যারান্টি'],
    specsEn: ['Genuine Mahogany Native Hardwood', 'Integrated Overhead Book Racks', 'Lockable File Storage Drawer', 'Scratch Resistant Matte Topcoat', '3-Year Premium Replacement Guarantee']
  },
  {
    id: 'coffee-table',
    nameBn: 'চিটাগাং সেগুন কাঠের নকশাদার চা টেবিল',
    nameEn: 'Traditional Teak Coffee Table',
    category: 'furniture',
    imgUrl: 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=800&q=80',
    priceRangeBn: '৮,০০০ - ৩০,০০০ ৳',
    priceRangeEn: '8,000 - 30,000 BDT',
    minPrice: 8000,
    descriptionBn: 'সোফা সেটের সামনে ড্রয়িং রুমের আভিজাত্য বজায় রাখার উপযোগী একটি দৃষ্টিনন্দন ও ছোট আকারের টি-টেবিল। এর চারপাশের আকর্ষণীয় খোদাই নকশা ও কাঁচের টপ রুমের পুরো রূপ পরিবর্তন করে দেবে।',
    descriptionEn: 'Anchor your sofa layout space with this compact hand-engraved classic Chittagong Teak central coffee table.',
    specsBn: ['চিটাগাং সেগুন কাঠ দ্বারা নির্মিত', '৭মিমি শক্তিশালী ডিজাইন গ্লাস', 'নিচে ম্যাগাজিন ও খবরের কাগজ রাখার র্যাক', 'মসৃণ সেগুন বার্নিশ টেক্সচার', 'সহজ ক্লিনিং হাই-গ্রাউন্ড'],
    specsEn: ['Assembled from Solid Teak', '7mm Toughened Clear Glass Top', 'Lower Classic Newspaper Rack', 'Hand-finished Wood Grain Varnish', 'High Ground Clearance for Clean Sweep']
  },
  {
    id: 'int-living',
    nameBn: 'রয়্যাল লাক্সারি ডুপ্লেক্স হোম ইন্টেরিয়র',
    nameEn: 'Sovereign Duplex Living Room',
    category: 'interior',
    imgUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=800&q=80',
    priceRangeBn: '২,৫০,০০০ ৳ থেকে শুরু',
    priceRangeEn: 'Starting from 250,000 BDT',
    minPrice: 250000,
    descriptionBn: 'স্পট এলইডি লাইটিং, দৃষ্টিনন্দন থ্রিডি রাজকীয় সেগুন উডেন ওয়াল প্যানেলিং এবং মেহগনি কাঠের আর্ট সিলিং এর অপূর্ব রাজকীয় ফিউশন। আমাদের প্রধান ডিজাইনার লিটন আলী স্যারের সরাসরি তদারকিতে সম্পন্ন এই লাক্সারি ইন্টেরিয়র কাজ।',
    descriptionEn: 'Luxury indirect profile LED lights, gorgeous 3D wood claddings, and tailored false ceiling installations supervised individually by Liton Ali.',
    specsBn: ['ইনডাইরেক্ট এলইডি লাইটিং সেটআপ', 'সেগুন কাঠের দৃষ্টিনন্দন থ্রিডি ওয়াল মোটিফ', 'সাউন্ডপ্রুফ সিলিং ব্যাকবোর্ড সাপোর্ট', '১০ বছরের কাজের গ্যারান্টি', 'সম্পূর্ণ কাস্টম সাইজ ডিজাইন'],
    specsEn: ['Premium Indirect Profile LEDs', '3D Solid Wood Board Claddings', 'Acoustically Stable False Ceilings', '10-Year Service Warranty', 'Tailored to Fit Your Hallway Dimensions'],
    isTrending: true
  },
  {
    id: 'int-kitchen',
    nameBn: 'বার্মিজ সেগুন মডুলার কিচেন ক্যাবিনেট',
    nameEn: 'Teak Modular Kitchen Cabinet',
    category: 'interior',
    imgUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80',
    priceRangeBn: '১,৮০,০০০ ৳ থেকে শুরু',
    priceRangeEn: 'Starting from 180,000 BDT',
    minPrice: 180000,
    descriptionBn: 'আর্দ্রতা ও পানি নিরোধক ওয়ান-গ্রেড প্রিমিয়াম ক্যাবিনেট বোর্ড। এর উপরিভাগে সেগুন কাঠের সূক্ষ্ম শিট এবং চকচকে হাই-গ্লস ল্যাকার ফিনিশিং যা খাবার ঘরকে করবে অত্যন্ত পরিষ্কার এবং আধুনিক। অটোমেটিক হাইড্রো সাইলেন্ট ট্র‍্যাক সমৃদ্ধ।',
    descriptionEn: 'High-moisture resistant premium fiberboard shell enveloped in seasoned Burma Teak veneers, featuring automatic quiet-close drawers.',
    specsBn: ['মরিচারোধী ট্রিপল হ্যাঙ্গিং ক্যাবিনেট', 'পানি ও বাষ্প প্রতিরোধী কোটিং শাইন', 'স্মার্ট কিচেন চিমনি স্পেস ফিটিং', 'অটো-সাইলেন্ট হাইড্রোলিক স্লাইডার', 'সম্পূর্ণ ফ্রী পরিমাপ মেজারমেন্ট'],
    specsEn: ['Anti-rust SS Utility Baskets', 'Steam and Vapor Impermeable Coat', 'Compatible Built-in Chimney Layout', 'Quiet-Close Hydraulic Tracks', 'Complimentary Measurement and Blueprinting']
  },
  {
    id: 'int-bedroom',
    nameBn: 'ইম্পেরিয়াল মাস্টার বেডরুম ওয়াল মেকিং',
    nameEn: 'Luxury Palace Bedroom Accent Wall',
    category: 'interior',
    imgUrl: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=800&q=80',
    priceRangeBn: '১,৫০,০০০ ৳ থেকে শুরু',
    priceRangeEn: 'Starting from 150,000 BDT',
    minPrice: 150000,
    descriptionBn: 'খাটের পেছনের দেয়ালে দৃষ্টিনন্দন রাজকীয় কাঠের বর্ডার ফ্রেম এবং ইম্পেরিয়াল হাই-লাইটিং আর্ট ট্রিম প্যানেলিং যা মাস্টার বেডরুমকে দিবে ফাইভ-স্টার রিসোর্টের মত চমৎকার এবং বিলাসবহুল রাজকীয় শান্ত পরিবেশ।',
    descriptionEn: 'Stately master bedroom wood carving borders, tufted backboards, and ambient backlighting structures rendering a 5-star resort environment.',
    specsBn: ['কাস্টম রাজকীয় কাঠের খোদাই বর্ডার ফ্রেম', 'কোজি ব্যাকলাইট ওয়ার্ম প্রোফাইল', 'হিডেন ডবল সাইড ড্রয়ার ড্রয়ারস', 'সেগুন কাঠ কিং মুকুট মোটিফ', 'অভিজাত ডিজাইনের কাপড় কোটিং'],
    specsEn: ['Custom Solid Carved Wood Boarder', 'Cozy Ambient Warm Backlighting Set', 'Integrated Concealed Dual Drawers', 'Master Crown Accent Teak Motifs', 'Exquisite Jacquard Fabric Tufting']
  }
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev1',
    name: 'আশরাফুল ইসলাম',
    rating: 5,
    date: '২০২৬-০৪-১০',
    comment: 'আবেদ ফার্ণিচার থেকে সোফা আর ডাইনিং টেবিল কিনেছি। মেহগনি কাঠের পলিশের ফিনিশিং এখনো একই রকম চমৎকার আছে। ডিলিং ও সার্ভিস চমৎকার!'
  },
  {
    id: 'rev2',
    name: 'নাদিম আহমেদ',
    rating: 5,
    date: '২০২৬-০৫-০১',
    comment: 'লিটন আলী ভাই আমাদের পুরো নতুন ফ্ল্যাটের ইন্টেরিয়র আর রাজকীয় কাঠের খাট বানিয়ে দিয়েছেন। দুবাই টেকে কাজের অভিজ্ঞতা উনার কাজে সত্যি ফুটে ওঠে!'
  },
  {
    id: 'rev3',
    name: 'ফারজানা ববি',
    rating: 4,
    date: '২০২৬-০৫-১৫',
    comment: 'স্লাইডিং আলমারির পারফরম্যান্স দারুণ, স্পেস অনেক সাশ্রয় করে। ডেলিভারি নির্ধারিত তারিখের একটু পরে পেলেও জিনিসপত্রের কোয়ালিটি অতুলনীয়!'
  }
];

export const TRANSLATIONS = {
  bn: {
    title: 'Abed Furniture and Interior',
    subtitle: 'প্রিমিয়াম কাঠের ফার্ণিচার ও ইন্টেরিয়র ডিজাইন',
    heroTag: 'আধুনিক ঘরের জন্য প্রিমিয়াম ফার্ণিচার',
    heroDesc: '১০ বছরেরও বেশি সময় ধরে গুণগতমান, টেকসই ডিজাইন এবং দীর্ঘস্থায়ী মেহগনি ও সেগুন কাঠের রাজকীয় ফার্ণিচার তৈরি করে আমরা আপনার আস্থা অর্জন করেছি।',
    browseFurniture: 'আমাদের ফার্ণিচার সমূহ',
    viewCatalog: 'পণ্য সামগ্রী দেখুন',
    all: 'সকল প্রডাক্ট',
    furniture: 'আসবাবপত্র (Furniture)',
    interior: 'ইন্টেরিয়র ডিজাইন (Interior)',
    searchPlaceholder: 'পণ্য খুঁজুন...',
    sortByPrice: 'মূল্য অনুসারে সাজান',
    defaultSort: 'ডিফল্ট সাজানো',
    priceLowHigh: 'মূল্য: কম থেকে বেশি',
    priceHighLow: 'মূল্য: বেশি থেকে কম',
    specs: 'বৈশিষ্ট্য সমূহ:',
    addToInquiry: 'ইনকোয়ারি লিস্টে যুক্ত করুন',
    addedToInquiry: 'যুক্ত হয়েছে',
    inquiryCartTitle: 'আপনার ইনকোয়ারি পণ্যসমূহ',
    noInquiryItems: 'ইনকোয়ারি লিস্টে এখনো কোনো পণ্য যুক্ত করেননি। অনুগ্রহ করে পণ্য তালিকার নিচে "যুক্ত করুন" প্রেস করুন।',
    customerInfoTitle: 'আপনার কন্টাক্ট ও রিকুয়েস্ট',
    fullName: 'আপনার সম্পূর্ণ নাম',
    phoneNumber: 'মোবাইল নম্বর',
    urgency: 'কাজের সময়সীমা',
    immediately: 'দ্রুত প্রয়োজন (১ সপ্তাহের মধ্যে)',
    oneMonth: '১ মাসের মধ্যে',
    justExploring: 'সাধারন অনুসন্ধান / দর কষাকষি',
    additionalNotes: 'विशेष কোনো চাহিদা বা কাস্টম সাইজ থাকলে লিখুন',
    sendWhatsApp: 'সরাসরি হোয়াটসঅ্যাপে বুকিং ও দর জানুন',
    designerHeader: 'প্রধান ডিজাইনার',
    designerTitle: 'প্রধান ডিজাইনার: লিটন আলী',
    designerExperience: 'দুবাই আরব টেক থেকে ৮ বছরের আন্তর্জাতিক অভিজ্ঞতা',
    designerDesc1: '১৫ বছরেরও বেশি সমৃদ্ধ অভিজ্ঞতা নিয়ে লিটন আলী আমাদের টিমে যুক্ত আছেন। উনার অন্যতম বিশেষত্ব হলো দুবাইয়ের বড় বড় কমার্শিয়াল ও লাক্সারি আরব প্রজেক্টে সফলতার সাথে ৮ বছর ডিজাইন কনসাল্ট্যান্ট হিসেবে কাজ করা।',
    designerDesc2: 'তিনি ক্লাসিক কাঠের খোদাই করা রাজকীয় নকশা থেকে শুরু করে বর্তমান যুগের আধুনিক স্পেস-সেভিং ফার্ণিচার ও ফ্ল্যাট ইন্টেরিয়রের দারুণ সমন্বয়ে দক্ষ। প্রতিটি নকশাই তিনি মেজারমেন্ট ও রুচি বুঝে স্পেশালি কাস্টমাইজ করেন।',
    experienceBadge: 'দুবাই আরব টেক অভিজ্ঞতাসম্পন্ন',
    contactTitle: 'যোগাযোগ ও শোরুমের অবস্থান',
    phoneCall: 'কল করুন',
    showroomAddress: 'শোরুমের ঠিকানা',
    addressDetails: 'গেন্ডারিয়া, ধূপখোলা মাঠ সংলগ্ন, ঢাকা, বাংলাদেশ (নির্দ্বিধায় শোরুমে ভিজিট করুন)',
    openingHours: 'খোলা থাকার সময়',
    hoursDetailsSatThu: 'শনিবার - বৃহস্পতিবার: সকাল ১০:০০ - রাত ৯:০০',
    hoursDetailsFri: 'শুক্রবার: বিকেল ৩:০০ - রাত ৯:০০',
    servicesTitle: 'আমাদের প্রিমিয়াম সেবাসমূহ',
    servicesList: ['কাস্টম ফার্ণিচার মেকিং', 'হোম ও অফিস ইন্টেরিয়র', 'ফ্রি প্রজেক্ট মেজারমেন্ট', 'সারা দেশে হোম ডেলিভারি'],
    reviewTitle: 'গ্রাহকদের সন্তুষ্টি পর্যালোচনা',
    addReviewBtn: 'আপনার মতামত দিন',
    writeReviewLabel: 'আপনার মন্তব্য লিখুন',
    ratingLabel: 'রেটিং',
    reviewerNameLabel: 'আপনার নাম',
    submitReview: 'মন্তব্য জমা দিন',
    thankYouReview: 'ধন্যবাদ! আপনার মূল্যবান মতামতটি সফলভাবে যুক্ত হয়েছে।',
    floatingCartTooltip: 'ইনকোয়ারি ব্যাগ',
    footerDesc: 'গুণগত মেহগনি ও সেগুন কাঠের ফার্ণিচার এবং চমৎকার ইন্টেরিয়র ডিজাইনের জন্য নির্ভরযোগ্য নাম। গ্যারান্টিযুক্ত কাঠের স্থায়িত্ব।',
    copyright: '© ২০২৬ আবেদ ফার্ণিচার ও ইন্টেরিয়র | সর্বস্বত্ব সংরক্ষিত',
    locationGmaps: 'গুগল ম্যাপে শোরুম খুঁজুন',
    styleQuizHeader: 'ডিজাইন স্টাইল সিলেক্টর',
    styleQuizSub: 'আপনার ঘরের জন্য কোন ভাইবটি পছন্দ? বেছে নিন এবং সেরা ফার্ণিচার জোড়া দেখুন!',
    selectVibe: 'আপনার ভাইব সিলেক্ট করুন',
    vibeClassic: 'ক্লাসিক রাজকীয় রূপ (Classic Carved)',
    vibeModern: 'আধুনিক মিনিমালিস্ট (Modern Sleek)',
    vibeSpaceSaving: 'জায়গা সাশ্রয়ী মডুলার (Space-saver)',
    vibeWoodys: 'নিখুঁত আদিম কাষ্ঠল ভাব (Pure Wooden Raw)',
    quizRecommendation: 'আপনার পছন্দের ভাইবের জন্য সেরা সুপারিশসমূহ:',
    totalEstimatedPrice: 'আনুমানিক মূল্য পরিসীমাঃ',
    addToInquiryList: 'সবগুলো ইনকোয়ারি ব্যাগে যুক্ত করুন'
  },
  en: {
    title: 'Abed Furniture & Interior',
    subtitle: 'Premium Wooden Furniture & Interior Design',
    heroTag: 'Premium Furniture Crafted for Modern Homes',
    heroDesc: 'For over 10 years, we have earned your trust with elegant designs, lifelong durability, and seasoned premium Teak and Mahogany wood formulations.',
    browseFurniture: 'Explore Our Collection',
    viewCatalog: 'Browse Catalogue',
    all: 'All Categories',
    furniture: 'Furniture Collection',
    interior: 'Interior Designs',
    searchPlaceholder: 'Search beautiful products...',
    sortByPrice: 'Sort by Price',
    defaultSort: 'Default Arrangement',
    priceLowHigh: 'Price: Low to High',
    priceHighLow: 'Price: High to Low',
    specs: 'Specifications:',
    addToInquiry: 'Add to Inquiry Bag',
    addedToInquiry: 'Added Successfully',
    inquiryCartTitle: 'Your Inquiry & Quote Setup',
    noInquiryItems: 'No items in the inquiry bag. Please explore our products below and click "Add to Inquiry Bag" to request custom quotes.',
    customerInfoTitle: 'Contact details & Preferences',
    fullName: 'Your Full Name',
    phoneNumber: 'Mobile Phone/WhatsApp Number',
    urgency: 'Project Timeline',
    immediately: 'Urgent (Within 1 week)',
    oneMonth: 'Within a Month',
    justExploring: 'Just exploring / Price estimation',
    additionalNotes: 'Custom cabinet sizes, wood species preference, or messages',
    sendWhatsApp: 'Send Quote-Request to WhatsApp',
    designerHeader: 'Principal Designer',
    designerTitle: 'Principal Designer: Liton Ali',
    designerExperience: '8 Years of Dubai Arab Tech International Expertise',
    designerDesc1: 'Liton Ali brings over 15 years of exceptional design craftsmanship. His crown jewel credentials include 8 years in Dubai as a lead designer and coordinator for large-scale premium Arabic residential projects.',
    designerDesc2: 'He specializes in combining glorious wooden patterns and robust carvings with sleek space-optimized custom fits. He personally drafts exact measurements matching individual family spatial layout demands.',
    experienceBadge: 'Dubai Arab Tech Alumni',
    contactTitle: 'Showroom Location & Contact Info',
    phoneCall: 'Click to Call',
    showroomAddress: 'Showroom Address',
    addressDetails: 'Gendaria, near Dhupkhola Play Ground, Dhaka, Bangladesh (Feel free to walk in and check wood quality)',
    openingHours: 'Showroom Hours',
    hoursDetailsSatThu: 'Saturday - Thursday: 10:00 AM - 09:00 PM',
    hoursDetailsFri: 'Friday: 03:00 PM - 09:00 PM',
    servicesTitle: 'Our Quality Offerings',
    servicesList: ['Bespoke Handmade Furniture', 'Residences & Office Interior design', 'On-site Measurements & Drafts', 'Islandwide Secured Shipping'],
    reviewTitle: 'Customer Testimonials',
    addReviewBtn: 'Leave a Review',
    writeReviewLabel: 'Write your comments here',
    ratingLabel: 'Rating',
    reviewerNameLabel: 'Your name',
    submitReview: 'Submit Review',
    thankYouReview: 'Thank you! Your verified customer testimonial was appended.',
    floatingCartTooltip: 'Inquiry Bag',
    footerDesc: 'A trusted brand creating luxury hand-carved mahogany and teak furniture since 2010. Guaranteed durability of materials and polishes.',
    copyright: '© 2026 Abed Furniture & Interior | All rights reserved',
    locationGmaps: 'Find us on Google Maps',
    styleQuizHeader: 'Home Design Style Matcher',
    styleQuizSub: 'Unsure which furniture suits your homes theme? Match your vibe and get direct recommendations!',
    selectVibe: 'Select Your Style Preference',
    vibeClassic: 'Classic Sovereign (Intricate Hand Carving)',
    vibeModern: 'Modern Minimalist (Sleek Golden accents)',
    vibeSpaceSaving: 'Compact Multi-utility (Modular fits)',
    vibeWoodys: 'Natural Raw Premium Wood Textures',
    quizRecommendation: 'Highly Recommended pieces for your chosen theme:',
    totalEstimatedPrice: 'Estimated Cost Bracket:',
    addToInquiryList: 'Add Recommended Items to Inquiry Bag'
  }
};
